### ISSUE TITLE
Manifests for Imports

### ISSUE THREAD

**Issue by ReneeHansen** [USEPA/e-manifest#1074]
Importers need to comply with 40 CFR 262.84(c), and need the ability to enter the importer's name, address & EPA ID into section 5, and the foreign generator's info in the site address of section 5.  The importer must complete section 16, the International Shipments block.  It does not appear that any of these things can be done in e-manifest.  Please add them.

**Comment by scottdchristian** [comment]
This functionality has been incorporated in both services and the front-end.  See the latest Services documentation on this site.
Thank you,
Scott
