### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by jerrysuggs** [USEPA/e-manifest#1144]
I have successfully uploaded several manifests.  I have compared this one to them and can't find anything wrong but I'm getting a system error.

{
  "code": "E_SystemError",
  "message": "System error occured",
  "errorId": "824584a7-8e11-471e-a434-bc3684aa58a9",
  "errorDate": "2018-06-21T18:29:09.620+0000"
}

I have attached the json and attachment.

Thanks,

Jerry

[sample_json.txt](https://github.com/USEPA/e-manifest/files/2124889/sample_json.txt)
[attachment-2.zip](https://github.com/USEPA/e-manifest/files/2124890/attachment-2.zip)

**Comment by scottdchristian** [comment]
On Thursday, these errors were from the load test.  I tested the site in my dev environment and had it work.
Thank you,
Scott

**Comment by jerrysuggs** [comment]
@scottdchristian  I tested on swagger just now and still got a 500.

**Comment by scottdchristian** [comment]
@jerrysuggs This is strange.  
Please send a screenshot and the full error.
Can you please try another TSDF and the same JSON? (It's the only change I made)
Do other JSON files work

**Comment by scottdchristian** [comment]
@jerrysuggs   I tried again in preprod with Swagger.  Again the only thing I changed was the TSDF and the Manifest tracking number and successfully sent the manifest.  
1) DO other files work
2) Please send a screen shot

**Comment by jerrysuggs** [comment]
@scottdchristian Sorry for the delay.  Yes we've gotten other files to upload fine.  And guess what...of course the sample works now with now changes.  I wonder if something got fixed that allowed it through.  If I run into this again I'll post the screenshot.

Thanks,

Jerry
