### ISSUE TITLE
EM-1849 originalSubmissionType not always set

### ISSUE THREAD

**Issue by e-manifest** [USEPA/e-manifest#1223]
originalSubmissionType is not being set in the following cases
* PPC creation of mail package
* Creation of correction version via Correct service <br><br> **Acceptance Criteria** <br> (x) originalSubmissionType is set to Image for PPC mail packages
(x) originalSubmissionType is copied from original version when new version is created via Correct service

**Comment by stevedonnelly5** [comment]
Does this impact hybrid manifests?
