### ISSUE TITLE
Various fixes for e-ManifestPy

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/e-manifest#1512]
@wiljnichepa, I was trying out the new user-search endpoint this weekeend, I've got a couple bug fixes and proposed changes.

backwards compatible
- [x] fix user-search url.

***Not*** backwards compatible
- [ ] fix [`GetHandler` method signature](https://github.com/USEPA/e-manifest/blob/9a4f8086fc1d736d83ade690103a7e46129a3d3a/emanifest-py/src/emanifest/client.py#L822) to `GetHandlerReg`
- [ ] Unpack the request's library `Response` object directly instead of embedding it in our own `RcraResponse` object
    - Pretty sure this was my doing. 
- [ ] rename the module `client` to `emanifest`
    - It's kinda clunky to have to do `from emanifest import client as em` since the term client is so vague. 
    - also my fault lol
  
Some of theses I have been sitting on for a while, b/c I didn't want to break backwards compatibility. However, I don't know how many people are actually using this library and we could probably sneak breaking changes in without any one noticing honestly lol.

**Comment by wiljnichepa** [comment]
Let's go ahead and do the backwards compatible bug fixes. 

I agree with the breaking suggestions but think we should do it in a second release with a note in the documentation about the changes, like we did with v1.1 vs. v2.0. Scott and I have been talking with folks who have implemented the package as part of an ETL workflow, so I'm hesitant to deploy any breaking changes without running it by them.

**Comment by dpgraham4401** [comment]
That's great new (that people outside of us are using this package) and I agree. I'll submit a PR for your review sometime this week.

**Comment by dpgraham4401** [comment]
I've converted these bullet points to issues and created a new milestone. Closing this discussion.
