### ISSUE TITLE
Auto-increment the python package number on upload via GitHub Action

### ISSUE THREAD

**Issue by wiljnichepa** [USEPA/e-manifest#1515]
@dpgraham4401 I was reviewing your improvements to the GitHub actions workflow to publish **emanifest** and wanted to explore additional upgrades in future releases:

- [ ] Auto-increment the package number on upload

**Comment by dpgraham4401** [comment]
I would also add, run the test suite prior to release. This will require mocking the responses which may be a pain in the rear.

**Comment by wiljnichepa** [comment]
Reading more about this (and in light of the accidental live test the other day) I think this is way too clever by half for the frequency with which we release new versions. The likelihood of messing something up far outweighs the slight benefit of updating the package number, and updating the package number is a good final checklist item to make sure things are set for release.
