### ISSUE TITLE
fix GetHandler method signature

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/e-manifest#1516]
fix [`GetHandler` method signature](https://github.com/USEPA/e-manifest/blob/9a4f8086fc1d736d83ade690103a7e46129a3d3a/emanifest-py/src/emanifest/client.py#L822) to `GetHandlerReg`.

If we decide to change the function/methods names to be PEP 8 compliant, then that corresponding name.

**Comment by wiljnichepa** [comment]
Closed by commit #1513
