### ISSUE TITLE
PEP 8 naming compliance? Discussion

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/e-manifest#1517]
Should we change the names of the RcraClient method to be PEP 8 compliant before releasing version 3.0?

I'm not a 'must-be-PEP-8-compliant' nut, but it's worth examining. I'm thinking  this is likely the last major release of the emanifest PyPi package, so if we're goin to change it, now is the time (and it's not really difficult to do).

**Comment by wiljnichepa** [comment]
I'm not a purist either, but if we're already going to make some breaking changes as part of a big release we might as well throw everything in. It will be the last major release for a while at least. The launch of V2 services at some point would definitely be a 4.0 release in my mind

**Comment by dpgraham4401** [comment]
Do we have a timeline, and, more importantly what changes are going to be introduced with the V2 revisions? There may be ways we can make emanifest 3.0 more flexible to accommodate the future changes.
