### ISSUE TITLE
Patch manifest methods do not send updates

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/e-manifest#1617]
The relatively new patch endpoint do not submit the body of the manifest in the client method,  [seen here](https://github.com/USEPA/e-manifest/blame/c82dbe91e0d5375cfc17944dfd7585b29e061ef7/emanifest-py/src/emanifest/client.py#L862C50-L862C50).

The `body` parameter is accepted but never sent as part of the HTTP request.

This is true in the [`patch_update_manifest`](https://github.com/USEPA/e-manifest/blob/c82dbe91e0d5375cfc17944dfd7585b29e061ef7/emanifest-py/src/emanifest/client.py#L862) method and the [`patch_correct_manifest`](https://github.com/USEPA/e-manifest/blob/c82dbe91e0d5375cfc17944dfd7585b29e061ef7/emanifest-py/src/emanifest/client.py#L876) method. 

@wiljnichepa Can you please correct this.

**Comment by wiljnichepa** [comment]
Thanks for spotting this. I've opened a PR to fix this.
