### ISSUE TITLE
404 Not found in production Get Manifest API response

### ISSUE THREAD

**Issue by megankirkbride** [USEPA/e-manifest#1623]
I'm attempting to use the api to get manifest data using this endpoint, `https://rcrainfopreprod.epa.gov/rcrainfo/rest/api/v1/emanifest/manifest/123456789ELC` and `https://rcrainfo.epa.gov/rcrainfo/rest/api/v1/emanifest/manifest/123456789ELC` but I'm noticing different behavior for each of these endpoints even though I'd expect them to behave the same way regardless of environment.

When I GET against the preprod environment, I receive and access denied error JSON response.
When I GET against the prod environment, I receive a 404 Not Found HTML response.

I noticed this when I was attempting to GET against the production environment with an authorization key and noticed I was getting a 404 regardless of what manifestId I used. 

Is this intentional? I'd expect prod to properly authenticate based on the authorization header included and I'd expect a response for the manifestId provided which should exist.

**Comment by wiljnichepa** [comment]
The production base URL is https://rcrainfo.epa.gov/rcrainfo**prod**/rest/api/. Please let us know if you still encounter the issue after making this update.

**Comment by megankirkbride** [comment]
> The production base URL is https://rcrainfo.epa.gov/rcrainfoprod/rest/api/. Please let us know if you still encounter the issue after making this update.

Thank you! I was hoping it was something minor like that!
