### ISSUE TITLE
Error - We are very sorry, but it looks like we've encountered a problem

### ISSUE THREAD

**Issue by shigepoi** [USEPA/e-manifest#413]
Conducting the "Post Registration Steps" from the Functional Mock Ups Available for Review email.  When searching for VA988177803.  I receive a red banner at the top of the page with the error reading "Error - We are very sorry, but it looks like we've encountered a problem".  

Therefore I cannot move forward to select Heating and Oil, etc.

**Comment by scottdchristian** [comment]
Thank you, the test environment was down for a little bit.  It is back up.
