### ISSUE TITLE
Transporter ID validation for IL State Only Transporters

### ISSUE THREAD

**Issue by e-manifest** [USEPA/e-manifest#853]
Per IL, there are transporters in IL that are handle state only wastes and do not have RCRAInfo IDs.  We need to accommodate for Transporters in IL that do not have IDs.

For a generator or TSDF in IL where only state waste is on the manifest the transporter ID can be null.
The IL special waste transporters do have a 4 digit, potentially a 3 digit number assigned to them by the state.

**Comment by drydevelopment** [comment]
@scottdchristian what's the status of this issue?

**Comment by drydevelopment** [comment]
From what I've been able to gather, Illinois does have a [Special Waste Haulers](http://epa.illinois.gov/topics/waste-management/waste-disposal/special-waste/transportation-permits/swhauler/index) lookup tool that can be used to assist in providing a _valid_ site address.  

However, this lookup tool does not provide a contact phone number, which is a required field based on 2.2 of the _"Save Update Delete Manifest services 7-11-2018.pdf"_

> 2.2. If the Transporter is not registered in RCRAInfo, then the following site information must be provided:
> - Site Address
> - Site Name
> - Contact phone

Is there any way to relax the API validation for _Contact phone_ not to be required when a transporter is not registered with RCRAInfo?

**Comment by scottdchristian** [comment]
As for phone number, we have a ticket to relax transporter information.  In the meantime you may enter a valid phone number
