### ISSUE TITLE
Container number

### ISSUE THREAD

**Issue by ChrisFSchmitt** [USEPA/e-manifest#887]
Would like to see a field addition when creating and modifying manifest to input the container size that are being shipped.  Currently, we do not have an field to indicate size of the containers, only type and quantity. 

Example  1DF, 5DF, 10DF, 15DF, 30DF, 55DF, 85DF, 95DF or a editable field to manually type the container size

**Comment by scottdchristian** [comment]
In the reference section, there is a field for this called container size.  It is a free form field.
Thank you
